version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: skibidi!
      MYSQL_DATABASE: MoonTech
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: skibidi!
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: apiuser
      DB_PASSWORD: skibidi!
      DB_NAME: MoonTech

volumes:
  db_data:
